services:
    api:
      build: ./backend
      env_file: ./backend/.env
      ports:
        - "3000:3000"
      depends_on:
          database:
            condition: service_healthy
    
    frontend:
      build: ./frontend
      ports:
        - "5173:5173"
      depends_on:
          - api

    database:
          image: postgres:15
          restart: always
          env_file : ./backend/.env
          ports:
            - "5432:5432"

          volumes:
            - database_db:/var/lib/postgresql/data
          healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB:-postgres}"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 10s


volumes:
  database_db: